<template>
    <article class="pa-5">
        <div id="write" class>
            <h1>
                <a name="江奶奶的galgame编辑器食用指南" class="md-header-anchor"></a>
                <span>江奶奶的Galgame编辑器食用指南</span>
            </h1>
            <h2>
                <a name="基本概念" class="md-header-anchor"></a>
                <span>基本概念</span>
            </h2>
            <p>
                <span>首先，与该编辑器与播放器（虽然还没完成）的用户有三个身份：开发者、作者、玩家：</span>
            </p>
            <ul>
                <li>
                    <strong>
                        <span>开发者</span>
                    </strong>
                    <span>：顾名思义，就是开发这个编辑器的人，当前只有江奶奶；</span>
                </li>
                <li>
                    <strong>
                        <span>作者</span>
                    </strong>
                    <span>：编辑剧本的作者，一般用的是编辑器；</span>
                </li>
                <li>
                    <strong>
                        <span>玩家</span>
                    </strong>
                    <span>：当一个作者完成一个剧本之后，游玩剧本的人，用的一般是播放器。</span>
                </li>
            </ul>
            <p>
                <span>在本编辑器，工程由三种主要数据构成：资源、角色、文本段。</span>
            </p>
            <h3>
                <a name="资源" class="md-header-anchor"></a>
                <span>资源</span>
            </h3>
            <p>
                <span>这里的资源，指的主要是多媒体资源，如：</span>
            </p>
            <ul>
                <li>
                    <span>以</span>
                    <code>.png</code>
                    <span>或</span>
                    <code>.jpg</code>
                    <span>等结尾的图片文件，</span>
                </li>
                <li>
                    <span>以</span>
                    <code>.ogg</code>
                    <span>或</span>
                    <code>.mp3</code>
                    <span>等结尾的音频文件，</span>
                </li>
                <li>
                    <span>以</span>
                    <code>.mp4</code>
                    <span>或</span>
                    <code>.wmv</code>
                    <span>等结尾的视频文件。</span>
                </li>
            </ul>
            <p>
                <span>该数据包含了三个主要字段：</span>
            </p>
            <ul>
                <li>
                    <strong>
                        <span>名字</span>
                    </strong>
                    <span>：一个资源的名字，但是这只是用于作者识别的，对于程序来说识别的标识是其ID，这在编译过程中会被舍弃；</span>
                </li>
                <li>
                    <strong>
                        <span>内容</span>
                    </strong>
                    <span>：这一般是作者从本地上传的上述多媒体文件的内容，要注意，如果文件过大，会导致内存占用过多。</span>
                </li>
            </ul>
            <p>
                <span>对于已有资源，其名字是可以改变的，其内容也是可以改变的。但是要知道，如果一个资源被删除，而后又新建了一个相同名字的资源的话，哪怕内容是一样的，也会</span>
                <strong>
                    <span>被认为是不同的资源</span>
                </strong>
                <span>！所以删除资源前请三思。</span>
            </p>
            <p>
                <strong>
                    <span>注意</span>
                </strong>
                <span>：</span>
            </p>
            <ol start>
                <li>
                    <span>人物立绘请使用</span>
                    <strong>
                        <span>png</span>
                    </strong>
                    <span>格式图片，因为该格式允许角色以外的空白部分呈现透明状态；</span>
                </li>
                <li>
                    <span>暂时</span>
                    <strong>
                        <span>不支持视频</span>
                    </strong>
                    <span>格式的使用，虽然你可以导入，但是这会导致大量的内存消耗，而且并不能用于剧本的编写；</span>
                </li>
                <li>
                    <span>音频也</span>
                    <strong>
                        <span>暂不支持</span>
                    </strong>
                    <span>，因为音频功能虽然计划加入，但是目前还没完成这部分的功能。</span>
                </li>
            </ol>
            <h3>
                <a name="角色" class="md-header-anchor"></a>
                <span>角色</span>
            </h3>
            <p>
                <span>作为一个Galgame的角色，该数据包含了三个主要字段：</span>
            </p>
            <ul>
                <li>
                    <strong>
                        <span>名字</span>
                    </strong>
                    <span>：一般来说，一个角色都会有名字，但是并不一定是一个名字对应一个角色（角色的）；</span>
                </li>
                <li>
                    <strong>
                        <span>头像</span>
                    </strong>
                    <span>：这个头像仅仅作为编辑器中方便作者直观地分辨角色的附属功能，会在编译为脚本的时候被舍弃；</span>
                </li>
                <li>
                    <strong>
                        <span>立绘</span>
                    </strong>
                    <span>：不用多说，要注意的是制作的时候，要注意统一画布大小，否则可能会出现大小以及像素的失真情况。</span>
                </li>
            </ul>
            <h3>
                <a name="文本段" class="md-header-anchor"></a>
                <span>文本段</span>
            </h3>
            <p>
                <span>这是一个江奶奶捏造的概念，如“文本段”这三个字一样，就是指文本段落，是一堆文本的合集。一个文本段相当于一般意义上的章节，包含一段完整或不完整的故事，但是同时又不太一样，因为一个文本段内，只能使用在一张背景。其长短没有指定，可以由几千行，也可以只有寥寥几行。</span>
            </p>
            <p>
                <span>这个数据结构，有以下几个重要字段：</span>
            </p>
            <ul>
                <li>
                    <strong>
                        <span>标题</span>
                    </strong>
                    <span>：这是作者识别文本段的内容的标识，这在编译过程中会被舍弃；</span>
                </li>
                <li>
                    <strong>
                        <span>副标题</span>
                    </strong>
                    <span>：目前仅仅是作为标题的注释一般，通常不必在意，这在编译过程中会被舍弃；</span>
                </li>
                <li>
                    <strong>
                        <span>背景</span>
                    </strong>
                    <span>：目前一个文本段只能由一张背景，一图流走到底，相当于</span>
                    <strong>
                        <span>传统</span>
                    </strong>
                    <span>舞台上的一个场景，不到拉幕就不会改变；</span>
                </li>
                <li>
                    <del>
                        <strong>
                            <span>BGM</span>
                        </strong>
                        <span>：背景音乐，没什么好说的，在一整个文本段持续的时间中都会循环播放该音频，该功能尚不完善，请忽略；</span>
                    </del>
                </li>
                <li>
                    <strong>
                        <span>小节列表</span>
                    </strong>
                    <span>：这是一个小节的有序列表，在玩家游玩的时候每一个小节会依序被显示在屏幕上，关于小节的详情见下文；</span>
                </li>
                <li>
                    <strong>
                        <span>出口列表</span>
                    </strong>
                    <span>：这是一个出口的集合，关于出口的详情见下文；</span>
                </li>
            </ul>
            <h4>
                <a name="小节" class="md-header-anchor"></a>
                <span>小节</span>
            </h4>
            <p>
                <span>一个小节主要由发言者与台词文本组成。发言者是从已有的角色中选择的一个，而台词文本是一段文字。</span>
            </p>
            <p>
                <span>关于台词文本，一个小节中的台词文本可以有多句组成，每行文本都会被视为一句台词，相当于是这个发言者连续说了多句台词。</span>
            </p>
            <h4>
                <a name="出口" class="md-header-anchor"></a>
                <span>出口</span>
            </h4>
            <p>
                <span>在游戏中，若一个文本段被播放完毕，这时候一般是场景的切换，或者玩家的选择，而可供玩家可以选择的选项就被称为这个文本段的出口。一个出口会对应一个文本段，该文本段将会在玩家选择了该出口后开始播放。</span>
            </p>
            <p>
                <span>每个出口都会有一段文本，用于提供给玩家进行选择，或者说是一种提示，而其会有一个与其相对应的目标，这个目标是从已经存在的文本段中选取的其中一个。</span>
            </p>
            <p>
                <span>附注：无论是资源、角色、文本段，都是以一个用户看不到的ID号码作为其唯一标识，所以哪怕是名字相同的资源、角色，也是被视为不同的两个或多个对象。</span>
            </p>
            <h2>
                <a name="食用步骤" class="md-header-anchor"></a>
                <span>食用步骤</span>
            </h2>
            <h3>
                <a name="完善基础信息" class="md-header-anchor"></a>
                <span>完善基础信息</span>
            </h3>
            <ol start>
                <li>
                    <span>点击左边导航栏的</span>
                    <code>基础信息</code>
                    <span>项目；</span>
                </li>
                <li>
                    <span>按照提示填补完善信息，完成后你会发现编辑面板上方（也就是菜单栏下方）的，该项目标签的文字右侧有一个实心原点，这代表该项目还未保存，此时按下</span>
                    <code>ctrl + S</code>
                    <span>保存当前项目，或者按下</span>
                    <code>ctrl + shift + S</code>
                    <span>保存所有项目，或者在菜单栏的</span>
                    <code>文件</code>
                    <span>下找到相应操作;</span>
                </li>
            </ol>
            <h3>
                <a name="准备资源" class="md-header-anchor"></a>
                <span>准备资源</span>
            </h3>
            <ol start>
                <li>
                    <span>点击左边导航栏的</span>
                    <code>资源管理器</code>
                    <span>项目；</span>
                </li>
                <li>
                    <span>准备好图片资源（毕竟现在也只支持图片资源XD），如头像、立绘、背景等；</span>
                </li>
                <li>
                    <span>将它们从电脑的资源管理器中拖入那个写有“拖拽或点击输入文件”且有文件图标的小框中，或者点击文件图标输入文件（推荐后者）；</span>
                </li>
                <li>
                    <span>拖进来后，在面板中会出现刚才拖入的资源，它们会自动根据文件名设置好自己的名字，如果不满意，可以自己修改名字，点击一下名字即可开始编辑，按下</span>
                    <code>Enter</code>
                    <span>键或者点击输入框以外的位置完成编辑；</span>
                </li>
                <li>
                    <span>如果有一些资源不满意，可以点击下方第二个按钮（总之不是那个长的像垃圾桶的就对了），然后重新输入文件（由于作用域的问题，请尽量点击图标正中）；</span>
                </li>
                <li>
                    <span>当你想要删除一些不必要的资源的时候，只要点击下方的垃圾桶图标即可，注意，</span>
                    <strong>
                        <span>这是不可逆的</span>
                    </strong>
                    <span>。</span>
                </li>
            </ol>
            <h3>
                <a name="创建角色" class="md-header-anchor"></a>
                <span>创建角色</span>
            </h3>
            <p>
                <span>当你设置完一些基础的素材后，便可以开始创建自己游戏中的角色了。</span>
            </p>
            <ol start>
                <li>
                    <span>点击左边导航栏的</span>
                    <code>角色</code>
                    <span>项目，展开角色列表；</span>
                </li>
                <li>
                    <span>点击最下边的</span>
                    <code>新建角色</code>
                    <span>按键，而后在右边就会打开这个新建角色的编辑面板（如果没有自动打开的话，就点一下列表中的角色）；</span>
                </li>
                <li>
                    <span>编辑名字，选择头像，选择立绘；</span>
                </li>
                <li>
                    <span>编辑完成后，保存该项目；</span>
                </li>
                <li>
                    <span>若想要删除该角色，只需要按下那个醒目的</span>
                    <code>删除该角色</code>
                    <span>按钮即可，注意，</span>
                    <strong>
                        <span>这是不可逆的</span>
                    </strong>
                    <span>！</span>
                </li>
                <li>
                    <span>想要关闭该项目，仅需在标签栏中关闭该项目的标签即可。</span>
                </li>
            </ol>
            <h3>
                <a name="编辑文本段" class="md-header-anchor"></a>
                <span>编辑文本段</span>
            </h3>
            <p>
                <span>连角色也创建好后，就可以正式开始写作了（其实之前的不做也没关系，大不了留空XD）。这也是这个编辑过程的重头戏。</span>
            </p>
            <ol start>
                <li>
                    <span>点击左边导航栏的</span>
                    <code>文本段</code>
                    <span>项目，展开文本段列表；</span>
                </li>
                <li>
                    <span>点击最下边的</span>
                    <code>新建文本段</code>
                    <span>按键，而后在右边就会打开这个新建文本段的编辑面板；</span>
                </li>
                <li>
                    <span>在编辑界面可以看到标题、副标题、背景的编辑区域，这些在上文已经介绍过了，按照所想编辑即可；</span>
                </li>
                <li>
                    <span>在背景的输入框下面，你还能看到一个“新出口”按键，这个先跳过，这在之后再使用；</span>
                </li>
                <li>
                    <span>点击下方的</span>
                    <code>新小节</code>
                    <span>按键，会在该按键上方多出一行小节面板；</span>
                </li>
                <li>
                    <span>在小节面板的左边是序号，而后是发言者，如果之前有创建角色并保存的话，这里就可以选择需要的角色，选择好后，其头像和名字将会显示出来（如果没有头像，则会用立绘代替头像显示）；</span>
                </li>
                <li>
                    <span>在发言者设置好后，再往右，就是文本框了，这里作者可以输入一行或多行文本，每一行都会被作为单独的台词呈现（游戏中同屏只会出现一句台词）；</span>
                </li>
                <li>
                    <span>如果鼠标位于该小节的编辑面板中的话，就会出现两个按钮：</span>
                    <code>+</code>
                    <span>与</span>
                    <code>-</code>
                    <span>，按下</span>
                    <code>+</code>
                    <span>按键，则可以在该小节</span>
                    <strong>
                        <span>前</span>
                    </strong>
                    <span>插入新的小节，按下</span>
                    <code>-</code>
                    <span>按键则会删除该小节；</span>
                </li>
                <li>
                    <span>而后重复上述操作，知道该文本段编写完毕，然后与编辑角色时候一样保存即可；</span>
                </li>
                <li>
                    <span>现在开始编辑出口，点击</span>
                    <code>新出口</code>
                    <span>按键，会出现一行新的出口面板，从左到右是：序号、文本输入框、目标选择框、删除按键，基本一看就懂，要注意文本框只能输入一行文本，目标选择框可以选择该出口对应的下一个文本段；</span>
                </li>
                <li>
                    <span>若要删除文本段，则点击右上角的三道杠按钮，然后会出现</span>
                    <code>删除</code>
                    <span>按钮，点击该按钮即可删除文本段，注意，</span>
                    <strong>
                        <span>这是不可逆的</span>
                    </strong>
                    <span>！</span>
                </li>
                <li>
                    <span>想要关闭该项目，仅需在标签栏中关闭该项目的标签即可。</span>
                </li>
            </ol>
            <p>
                <span>另外，在编辑小节的文本的时候，</span>
            </p>
            <ul>
                <li>
                    <span>按下</span>
                    <code>ctrl + Enter（回车）</code>
                    <span>，则是自动在该小节后插入一个新的小节，并聚焦到这个新的小节上；</span>
                </li>
                <li>
                    <span>按下</span>
                    <code>ctrl + BackSpace（退格）</code>
                    <span>且该小节文本都是空的（或者由空字符组成），则该小节将被删除并合并到上一个小节（如果存在的话）；</span>
                </li>
                <li>
                    <span>按下</span>
                    <code>ctrl + ArrowUp（上箭头）</code>
                    <span>，则聚焦到上一个小节（如果存在的话）；</span>
                </li>
                <li>
                    <span>按下</span>
                    <code>ctrl + ArrowDown（下箭头）</code>
                    <span>，则聚焦到下一个小节（如果存在的话）。</span>
                </li>
                <li>
                    <span>按下</span>
                    <code>ctrl + ArrowDown（左箭头）</code>
                    <span>，切换发言者为角色列表的上一个角色（如果存在的话）。</span>
                </li>
                <li>
                    <span>按下</span>
                    <code>ctrl + ArrowDown（右箭头）</code>
                    <span>，切换发言者为角色列表的下一个角色（如果存在的话）。</span>
                </li>
            </ul>
            <h3>
                <a name="持久化" class="md-header-anchor"></a>
                <span>持久化</span>
            </h3>
            <p>
                <span>编辑过程中有两个概念：工程与脚本：</span>
            </p>
            <ul>
                <li>
                    <strong>
                        <span>工程</span>
                    </strong>
                    <span>：这是作者写作时候，用编辑器编辑的工程文件，并不能直接游玩；</span>
                </li>
                <li>
                    <strong>
                        <span>脚本</span>
                    </strong>
                    <span>：当一个作者完成一个剧本之后，会将其编译为脚本，而后可以在播放器或者编辑器自带的测试面板中游玩。</span>
                </li>
            </ul>
            <p>
                <span>之前的保存操作，其实是将内容缓存到了浏览器自带的一个叫做</span>
                <code>LocalStorage</code>
                <span>的地方，如果浏览器清理缓存，或者更换了新的计算机、新的浏览器、新的域名，那么该数据就找不到了。所以为了更好的持久化，还是要将工程下载到能看得到的地方。</span>
            </p>
            <p>
                <span>所以在菜单栏下点击</span>
                <code>文件</code>
                <span>下的</span>
                <code>下载工程</code>
                <span>或者</span>
                <code>下载脚本</code>
                <span>完成相应操作，要注意，</span>
                <code>下载脚本</code>
                <span>按键只有在有已经编译完成的脚本时候才可用。当你下一次想要在别的计算机或者浏览器载入工程的时候，只要有改文件即可载入。</span>
            </p>
            <h3>
                <a name="编译" class="md-header-anchor"></a>
                <span>编译</span>
            </h3>
            <p>
                <span>想要最终得到一个可以游玩的脚本，就需要这个叫做编译的过程。它将一个工程内的数据进行整理、编号、排序、简化、链接，最终得到一份可以游玩的游戏脚本文件。在菜单栏下点击</span>
                <code>工程</code>
                <span>下的</span>
                <code>编译为测试版</code>
                <span>完成相应操作。编译后的脚本将会缓存在内存中，如果不下载，那么在浏览器关闭，甚至该页面关闭之后，该脚本就会消失，但是这并不可怕，由于工程还在，所以只要重新编译即可。可以在在菜单栏下点击</span>
                <code>文件</code>
                <span>下的</span>
                <code>下载脚本</code>
                <span>以下载编译好的脚本。</span>
            </p>
            <h2>
                <a name="最后" class="md-header-anchor"></a>
                <span>最后</span>
            </h2>
            <blockquote>
                <p>
                    <span>子未曰：“Hava a gada daya!”</span>
                </p>
            </blockquote>
        </div>
    </article>
</template>